sudo: false

language: java

cache:
 directories:
 - $HOME/.m2/repository

jdk:
 - oraclejdk7
 - openjdk7
 - openjdk6
 - oraclejdk8

install: travis_wait mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
